export const products = [
  {
    name: "The Witcher 3: Wild Hunt",
    image: "images/witcher.png",
    genre: "RPG",
    price: 39.99,
    releaseDate: "2015-05-18",
    sale: true,
    publisher: "CD Projekt Red",
  },
  {
    name: "Cyberpunk 2077",
    image: "images/cyberpunk.png",
    genre: "RPG",
    price: 59.99,
    releaseDate: "2020-12-10",
    sale: false,
    publisher: "CD Projekt Red",
  },
  {
    name: "Hades",
    image: "images/hades.png",
    genre: "Rogue-like",
    price: 24.99,
    releaseDate: "2020-09-17",
    sale: true,
    publisher: "Supergiant Games",
  },
  {
    name: "Stardew Valley",
    image: "images/stardew.png",
    genre: "Simulation",
    price: 14.99,
    releaseDate: "2016-02-26",
    sale: false,
    publisher: "ConcernedApe",
  },
  {
    name: "DOOM Eternal",
    image: "images/doom.png",
    genre: "FPS",
    price: 59.99,
    releaseDate: "2020-03-20",
    sale: true,
    publisher: "Bethesda",
  },
  {
    name: "Celeste",
    image: "images/celeste.png",
    genre: "Platformer",
    price: 19.99,
    releaseDate: "2018-01-25",
    sale: false,
    publisher: "Matt Makes Games",
  },
  {
    name: "Hollow Knight",
    image: "images/hollowknight.png",
    genre: "Metroidvania",
    price: 14.99,
    releaseDate: "2017-02-24",
    sale: true,
    publisher: "Team Cherry",
  },
  {
    name: "Among Us",
    image: "images/amongus.png",
    genre: "Party",
    price: 4.99,
    releaseDate: "2018-06-15",
    sale: false,
    publisher: "Innersloth",
  },
  {
    name: "Red Dead Redemption 2",
    image: "images/rdr2.png",
    genre: "Action-Adventure",
    price: 59.99,
    releaseDate: "2018-10-26",
    sale: true,
    publisher: "Rockstar Games",
  },
  {
    name: "Minecraft",
    image: "images/minecraft.png",
    genre: "Sandbox",
    price: 26.95,
    releaseDate: "2011-11-18",
    sale: false,
    publisher: "Mojang",
  },
  {
    name: "The Legend of Zelda: Breath of the Wild",
    image: "images/zelda.png",
    genre: "Adventure",
    price: 59.99,
    releaseDate: "2017-03-03",
    sale: false,
    publisher: "Nintendo",
  },
  {
    name: "Animal Crossing: New Horizons",
    image: "images/animalcrossing.png",
    genre: "Simulation",
    price: 59.99,
    releaseDate: "2020-03-20",
    sale: false,
    publisher: "Nintendo",
  },
  {
    name: "Final Fantasy VII Remake",
    image: "images/finalfantasy.png",
    genre: "RPG",
    price: 69.99,
    releaseDate: "2020-04-10",
    sale: true,
    publisher: "Square Enix",
  },
  {
    name: "Dark Souls III",
    image: "images/darksouls.png",
    genre: "Action RPG",
    price: 59.99,
    releaseDate: "2016-03-24",
    sale: true,
    publisher: "FromSoftware",
  },
  {
    name: "Fortnite",
    image: "images/fortnite.png",
    genre: "Battle Royale",
    price: 0.0,
    releaseDate: "2017-07-21",
    sale: false,
    publisher: "Epic Games",
  },
  {
    name: "Call of Duty: Modern Warfare",
    image: "images/cod.png",
    genre: "FPS",
    price: 59.99,
    releaseDate: "2019-10-25",
    sale: true,
    publisher: "Activision",
  },
  {
    name: "Ghost of Tsushima",
    image: "images/ghost.png",
    genre: "Action-Adventure",
    price: 59.99,
    releaseDate: "2020-07-17",
    sale: false,
    publisher: "Sony Interactive Entertainment",
  },
  {
    name: "Rocket League",
    image: "images/rocketleague.png",
    genre: "Sports",
    price: 0.0,
    releaseDate: "2015-07-07",
    sale: false,
    publisher: "Psyonix",
  },
  {
    name: "Apex Legends",
    image: "images/apex.png",
    genre: "Battle Royale",
    price: 0.0,
    releaseDate: "2019-02-04",
    sale: false,
    publisher: "Respawn Entertainment",
  },
  {
    name: "Persona 5 Royal",
    image: "images/persona.png",
    genre: "RPG",
    price: 59.99,
    releaseDate: "2020-03-31",
    sale: true,
    publisher: "Atlus",
  },
];
