export const products = [
  {
    name: "The Witcher 3: Wild Hunt",
    genre: "RPG",
    price: 39.99,
    releaseDate: "2015-05-18",
    sale: true,
    publisher: "CD Projekt Red",
  },
  {
    name: "Cyberpunk 2077",
    genre: "RPG",
    price: 59.99,
    releaseDate: "2020-12-10",
    sale: false,
    publisher: "CD Projekt Red",
  },
  {
    name: "Hades",
    genre: "Rogue-like",
    price: 24.99,
    releaseDate: "2020-09-17",
    sale: true,
    publisher: "Supergiant Games",
  },
  {
    name: "Stardew Valley",
    genre: "Simulation",
    price: 14.99,
    releaseDate: "2016-02-26",
    sale: false,
    publisher: "ConcernedApe",
  },
  {
    name: "DOOM Eternal",
    genre: "FPS",
    price: 59.99,
    releaseDate: "2020-03-20",
    sale: true,
    publisher: "Bethesda",
  },
  {
    name: "Celeste",
    genre: "Platformer",
    price: 19.99,
    releaseDate: "2018-01-25",
    sale: false,
    publisher: "Matt Makes Games",
  },
  {
    name: "Hollow Knight",
    genre: "Metroidvania",
    price: 14.99,
    releaseDate: "2017-02-24",
    sale: true,
    publisher: "Team Cherry",
  },
  {
    name: "Among Us",
    genre: "Party",
    price: 4.99,
    releaseDate: "2018-06-15",
    sale: false,
    publisher: "Innersloth",
  },
  {
    name: "Red Dead Redemption 2",
    genre: "Action-Adventure",
    price: 59.99,
    releaseDate: "2018-10-26",
    sale: true,
    publisher: "Rockstar Games",
  },
  {
    name: "Minecraft",
    genre: "Sandbox",
    price: 26.95,
    releaseDate: "2011-11-18",
    sale: false,
    publisher: "Mojang",
  },
  {
    name: "The Legend of Zelda: Breath of the Wild",
    genre: "Adventure",
    price: 59.99,
    releaseDate: "2017-03-03",
    sale: false,
    publisher: "Nintendo",
  },
  {
    name: "Animal Crossing: New Horizons",
    genre: "Simulation",
    price: 59.99,
    releaseDate: "2020-03-20",
    sale: false,
    publisher: "Nintendo",
  },
  {
    name: "Final Fantasy VII Remake",
    genre: "RPG",
    price: 69.99,
    releaseDate: "2020-04-10",
    sale: true,
    publisher: "Square Enix",
  },
  {
    name: "Dark Souls III",
    genre: "Action RPG",
    price: 59.99,
    releaseDate: "2016-03-24",
    sale: true,
    publisher: "FromSoftware",
  },
  {
    name: "Fortnite",
    genre: "Battle Royale",
    price: 0.0,
    releaseDate: "2017-07-21",
    sale: false,
    publisher: "Epic Games",
  },
  {
    name: "Call of Duty: Modern Warfare",
    genre: "FPS",
    price: 59.99,
    releaseDate: "2019-10-25",
    sale: true,
    publisher: "Activision",
  },
  {
    name: "Ghost of Tsushima",
    genre: "Action-Adventure",
    price: 59.99,
    releaseDate: "2020-07-17",
    sale: false,
    publisher: "Sony Interactive Entertainment",
  },
  {
    name: "Rocket League",
    genre: "Sports",
    price: 0.0,
    releaseDate: "2015-07-07",
    sale: false,
    publisher: "Psyonix",
  },
  {
    name: "Apex Legends",
    genre: "Battle Royale",
    price: 0.0,
    releaseDate: "2019-02-04",
    sale: false,
    publisher: "Respawn Entertainment",
  },
  {
    name: "Persona 5 Royal",
    genre: "RPG",
    price: 59.99,
    releaseDate: "2020-03-31",
    sale: true,
    publisher: "Atlus",
  },
];
